### ISSUE TITLE
Can't seem to be able to couple the Beagle with the PC/smartphone

### ISSUE THREAD

**Issue by Cris70** [schierla/jbeagle#4]
Hi, Txtr software is now non-functional so I uninstalled it from the phone. After resetting the beagle and putting it into pairing mode, it seems I am not able to pair it with anything.
I tried it with my laptop (both using Linux and Windows 10) and with my phone.
Both the laptop and the phone say they paired successfully with the Beagle, but the Beagle keep saying "Pairing with your smartphone". Do you have any trick to pair successfully?
Thank you in advance.
Cris

**Comment by schierla** [comment]
Actually, resetting should not be required to use jBeagle. On my computer, I can pair the beagle with Windows 10 (using the bluetooth key 0000); however my beagle already displays "Waiting for books". You can try to start jBeagle when windows/linux thinks the beagle is paired; maybe setting the partner ID (which happens when jBeagle connects to a virgin beagle) will do the trick.

**Comment by Cris70** [comment]
I had to reset it because it was paired with the Txtr app on my phone and I
could not unpair it because I removed the Txtr app long ago before I
discovered your software.
I can try again using the bt key 0000 (but IIRC that's what I was already
using).
What do you mean by "maybe setting the partner ID"? How do I do it?

**Comment by schierla** [comment]
Simply try to start jBeagle, maybe that's all it takes.
(Actually I think jBeagle works even while the beagle is paired with the txtr app, 
however it's been a long time since I used the txtr app so I can't tell for sure)

**Comment by Cris70** [comment]
OK, now I have another problem (don't yet know if the first is solved):
jBeagle always tells me that the bluetooth stack is not detected.

I launch it this way:
java -cp
.;bluecove-2.1.1-SNAPSHOT.jar;bluecove-gpl-2.1.1-SNAPSHOT.jar;jzlib-1.1.3.zip
-jar jbeagle-0.1.2.jar

Is it correct?

Also, jpedal is not free anymore. It is not on sourceforge anymore. I
requested a 30-day trial just to try jBeagle, let's see if/when they send
me the link to download. Is jpedal necessary to start jBeagle?

Sorry for being such a noob :-)

Cris

**Comment by schierla** [comment]
Just go to the releases page here at github and download version 0.1.2
It should include all the required libraries at least for Windows.

**Comment by Cris70** [comment]
That's exactly where I got my copy of jBeagle. I tried to start it simply with "java -jar jbeagle-1.2.jar", but this is still a no go. I still have "Error: Bluetooth Stack not detected" when starting jBeagle.
This is on Windows 10 with java 1.8.0_65.

![jbeagle](https://cloud.githubusercontent.com/assets/5107224/11274128/84dcf1be-8ed7-11e5-8c29-6d9fef0bbc43.png)

**Comment by schierla** [comment]
So Windows correctly detects your bluetooth device (I get this error when I unplug my Bluetooth dongle)?
Are you using the 32bit or 64bit version of Java?

**Comment by Cris70** [comment]
Sorry for being so late.
I am using 64 bit version.

Cris

**Comment by schierla** [comment]
Unfortunately, I cannot reproduce the problem. 
Here it works with both the current 32 bit and 64 bit version.
Do you get any console output when starting it in a console using "java -jar jbeagle-0.1.2.jar"?

**Comment by Warlord711** [comment]
Hi ! I found my old beagle today ! Thanks for the project !

I did found that the device has a low range, so it took me a moment to realize that and by positioning the device next to my bluetooth dongle, I was able to connect and delete+upload content ! On Win10 1909 64bit, using Eclipse+64bit Java.

I changed the pom.xml, because the bluecove repository was no longer valid:

`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>de.schierla</groupId>
	<artifactId>jbeagle</artifactId>
	<version>0.1.1-SNAPSHOT</version>
	<name>jBeagle</name>
	<description>Java application for managing the txtr beagle</description>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>de.schierla.jbeagle.ui.JBeagle</mainClass>
						</manifest>
					</archive>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.8</version>
		</dependency>
		<dependency>
			<groupId>com.jcraft</groupId>
			<artifactId>jzlib</artifactId>
			<version>1.1.2</version>
		</dependency>
		<dependency>
			<groupId>jpedal</groupId>
			<artifactId>jpedal</artifactId>
			<version>4.45-b-105</version>
		</dependency>
		<dependency>
			<groupId>bluecove</groupId>
			<artifactId>bluecove</artifactId>
			<version>2.1.1-SNAPSHOT</version>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>geomajas</id>
			<url>http://maven.geomajas.org/</url>
		</repository>
		<repository>
			<id>pyx4me-web-snapshot</id>
			<url>http://akci.coli.uni-saarland.de/artifactory/external/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<releases>
				<enabled>false</enabled>
			</releases>
		</repository>
	</repositories>
</project>`
